osx_image: xcode9.3

language: objective-c

xcode_project: FoodTracker.xcodeproj
xcode_scheme: FoodTracker
xcode_sdk: iphonesimulator9.3

branches:
  only:
    - master

notifications:
  email:
    on_success: change
    on_failure: always
