osx_image: xcode9.3

language: objective-c

xcode_workspace: FoodTracker.xcworkspace
xcode_scheme: FoodTracker

cache:
  directories:
  - Carthage

script: 
  - carthage update --platform iOS
  - xcodebuild test -workspace FoodTracker.xcworkspace -scheme FoodTracker -destination 'platform=iOS Simulator,name=iPhone 8 Plus,OS=11.3'
